# 应用服务 WEB 访问端口
spring:

  redis:
    host:localhost
    port:6379
  # password: your_password
  # database: 0

  datasource:
    url: jdbc:mysql://localhost:3306/springSecurity?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: mqwmysql
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
server:
  port: 8888


